; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:TWIFI_ARDESP32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

; 1. Forza il pinout delle scritte sulla scheda
board_build.pinout = arduino
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0
board_build.filesystem = littlefs  

upload_protocol = espota
;upload_port = 10.0.1.136 ; 26001
;upload_port = 10.0.1.149 ; 26002 
;upload_port = 10.0.3.198 ; 26003 
;upload_port = 10.0.3.32 ; 26004 
upload_port = 10.0.3.107 ; 26005 
;upload_port = 10.0.1.235 ; 26006 
;upload_port = 10.0.2.76 ; 26007  

; 2. Gestione della porta USB nativa per evitare il freeze all'avvio
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D SERIAL_NR=\"26005\"

lib_deps =
    esp32async/AsyncTCP@^3.4.10
    esp32async/ESPAsyncWebServer@^3.11.0
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit MAX31865 library @ ^1.6.2
    olikraus/U8g2 @ ^2.35.19

    
 

    