@startuml
title Diagramma di stato - Task Network
[*] --> wifi_start

state wifi_start {
   wifi_start: avvia connessione
}

state wifi_wait
state wifi_idle

state ap_mode_start {
   ap_mode_start: avvia access point
}

state ap_mode_idle

wifi_start --> ap_mode_start : if wifi_ssid = ""
wifi_start --> wifi_wait : richiesta effettuata
wifi_wait --> wifi_wait : loop attesa connessione
wifi_wait --> wifi_idle : wifi connected 
wifi_wait --> ap_mode_start : if timout > 10 sec
wifi_idle --> wifi_start : wifi not connected || resetNetwork
wifi_idle --> wifi_idle : loop monitoraggio connessione
ap_mode_start --> ap_mode_idle
ap_mode_idle --> wifi_start : resetNetwork
ap_mode_idle --> ap_mode_idle : loop attesa resetNetwork 

@enduml