@startuml
title Diagramma di stato - Task Display

[*] --> display_idle

state display_idle {
   display_idle: leggi var globali
   display_idle: aggiorna display
   display_idle: ripeti dopo 200 ms
}

state display_deep_sleep {
   display_deep_sleep: lampeggia 3 volte 
}

display_idle --> display_idle : deepSleep == false
display_idle --> display_deep_sleep : deepSleep == true
@enduml