@startuml TaskWeb_State_Machine
title FMW_TWIFI_ARDESP32 v. 1.2  - Task Web
[*] --> webserver_start

state webserver_start
webserver_start : * Programma callback routes 
webserver_start : * Avvia WebServer e WS
webserver_start --> webserver_idle : server avviato


state webserver_idle
webserver_idle : * Send sensor data to websockets
webserver_idle --> webserver_stop : Segnale resetWeb
webserver_idle --> webserver_idle : lettura inviata

state webserver_stop
webserver_stop : * Send closeAll signal
webserver_stop --> webserver_stop : ws.count() > 0
webserver_stop : * Remove wsocket handle and shutdown webserver
webserver_stop --> webserver_start : webserver down

@enduml