@startuml
title FMW_TWIFI_ARDESP32 v. 1.2 - Task MQTT

[*] --> mqtt_start 

state mqtt_start 
mqtt_start : * Update global status
mqtt_start : * Begin connection
mqtt_start : * Set connection timeout
mqtt_start --> mqtt_start : Network OFF
mqtt_start --> mqtt_wait : Network ON

state mqtt_wait 
mqtt_wait --> mqtt_idle : Connected
mqtt_wait --> mqtt_start : expired timeout 5 sec

state mqtt_idle
mqtt_idle : * Send JSON data 
mqtt_idle : * Blink blue led
mqtt_idle : * Set delay timeout
mqtt_idle --> mqtt_start : Connection lost
mqtt_idle --> mqtt_idle : repeat after 5 sec 


@enduml